hikaya/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hikaya.Controllers
{
    public class PartialController : Controller
    {
        // GET: Partial
        public ActionResult search()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult search(string search)
        {
            return PartialView();
        }
    }
}

hikaya/Controllers/SavedStoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hikaya.Models;
namespace hikaya.Controllers
{
    public class SavedStoriesController : Controller
    {
        // GET: SavedStories
        HikayaContext db = new HikayaContext();
        public ActionResult Index()
        {
            List<SavedStory> saveds = db.SavedStories.ToList();
            List<Story> stories = db.Stories.ToList();
            List<User> users = db.Users.ToList();
            List<Story> sts = new List<Story>();
            int userid = int.Parse(Session["userid"].ToString());
            foreach (var item in saveds)
            {
                Story s1 = stories.Where(n => n.id == item.storyid && item.userid==userid).FirstOrDefault();
                if (s1 != null)
                {
                    sts.Add(s1);
                }
                
            }
            ViewBag.users = users;
            return View(sts);
        }
        public ActionResult add(int id)
        {
            Story s = db.Stories.Where(n => n.id == id).FirstOrDefault();
            SavedStory ss = new SavedStory();
            ss.storyid = id;
            ss.userid = int.Parse(Session["userid"].ToString());
            db.SavedStories.Add(ss);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult unSave(int id)
        {
            Story s = db.Stories.Where(n => n.id == id).FirstOrDefault();
            int userid = int.Parse(Session["userid"].ToString());
            SavedStory ss = db.SavedStories.Where(n => n.userid == userid && n.storyid ==s.id ).FirstOrDefault();

            db.SavedStories.Remove(ss);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

hikaya/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hikaya.Models;
namespace hikaya.Controllers
{
    public class StoryController : Controller
    {
        // GET: Story
        HikayaContext db = new HikayaContext();
        public ActionResult display()
        {
            List<Story> sts;
            int? userid = (int)Session["userid"];
            sts = db.Stories.Where(n => n.userid == userid).ToList();
            return View(sts);
        }
        public ActionResult create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult create(Story s)
        {
            s.userid = (int)Session["userid"];
            s.isPublished = false;
            db.Stories.Add(s);
            db.SaveChanges();
            return RedirectToAction("display");
        }
        public ActionResult addPlot(int id)
        {
            Session["storyid"] = id;
            return View();
        }
        [HttpPost]
        public ActionResult addPlot(StoryPlot s,HttpPostedFileBase photo)
        {
            s.storyid = (int)Session["storyid"];
            if(photo != null)
            {
                s.imageUrl = photo.FileName;
                photo.SaveAs(Server.MapPath("~/attached/" + photo.FileName));
            }
            db.StoryPlots.Add(s);
            db.SaveChanges();
            return RedirectToAction("display");
        }
        public ActionResult viewStory(int id)
        {            
            Story s = db.Stories.Where(n => n.id == id).FirstOrDefault();
            List<StoryPlot> sts = db.StoryPlots.Where(n => n.storyid == id).ToList();
            List<FeaturedMessage> msgs = db.FeaturedMessages.Where(n => n.storyid == id).ToList();
            ViewBag.msgs = msgs;
            StoryAndPlots sp = new StoryAndPlots() { story = s, plots = sts };
            return View(sp);
        }
        public ActionResult removeStory(int id)
        {
            Story s = db.Stories.Where(n => n.id == id).FirstOrDefault();
            db.Stories.Remove(s);
            db.SaveChanges();
            return RedirectToAction("display");
        }
        public ActionResult editPlot(int id)
        {
            StoryPlot sp = db.StoryPlots.Where(n => n.id == id).FirstOrDefault();
            Session["storyid"] = sp.storyid;
            Session["plotImage"] = sp.imageUrl;
            return View(sp);
        }
        [HttpPost]
        public ActionResult editPlot(StoryPlot s, HttpPostedFileBase photo)
        {
            s.storyid = (int)Session["storyid"];
            if (photo != null)
            {
                s.imageUrl = photo.FileName;
                photo.SaveAs(Server.MapPath("~/attached/" + photo.FileName));
            }
            else
            {
                s.imageUrl = Session["plotImage"].ToString();
            }
            db.Entry(s).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("display");
        }
    }
}

hikaya/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hikaya.Models;

namespace hikaya.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        HikayaContext db = new HikayaContext();
        public ActionResult display()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(User u)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(u);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult logout()
        {
            Session["isAdmin"] = "false";
            Session["userid"] = null;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(User u)
        {
            User u1 = db.Users.Where(n => n.email == u.email && n.password == u.password).FirstOrDefault();
            Session["isAdmin"] = "false";
            if (u1 != null)
            {
                Admin a = db.Admins.Where(n => n.id == u1.id).FirstOrDefault();
                if (a != null)
                {
                    Session["isAdmin"] = "true";
                }
                Session["userid"] = u1.id;
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public ActionResult writer(int id)
        {
            List<Story> sts = db.Stories.Where(n => n.userid == id && n.isPublished==true).ToList();
            ViewBag.username = db.Users.Where(n => n.id == id).FirstOrDefault().name;
            return View(sts);
        }
    }
}

hikaya/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="~/wwwroot/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:0;min-height:80vh">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Hikaya", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse" data-bs-target="#navmenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navmenu" class="collapse navbar-collapse">
                <ul class="navbar-nav ms-auto">
                    @if (Session["userid"] != null)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("My Stories", "display", "Story", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                        if (Session["isAdmin"].ToString() == "true")
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Approve Stories", "display", "Admin", new { area = "" }, new { @class = "navbar-brand" })
                            </li>
                        }

                        <li class="nav-item">
                            @Html.ActionLink("Saved Stories", "Index", "SavedStories", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("logout", "logout", "User", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("register", "create", "User", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("login", "login", "User", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                    }
                    @*<li class="nav-item">
                    @{
                        Html.RenderAction("search", "Partial");
                    }
                </li>*@
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container body-content">
        <div class="p-5" style="min-height: 76vh">
            @RenderBody()
        </div>
        
        <hr />
        <footer>
            <p>&copy; 2021 - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>